---
title: "20210210 Call list generator"
author: "cheungngo"
date: "2/10/2021"
output: html_document
---

```{r}
# Loading the data

library(readxl)
raw <- read_excel("call_gen_input.xlsx") ### need to save the input file as this name every time
raw
```

```{r}
set.seed(20210210) ### to be changed each time
```

```{r}
### Setting up the result var

which(raw$day=="NA")[1]
result = rep(NA, which(raw$day=="NA")[1] - 1)
result = as.array(result)
dim(result)

### Isolating other variables

ind_count = which(raw$index=="count")
count = raw[ind_count, 3:dim(raw)[2]]
count

wecount = raw[which(raw$index=="wecount"), 3:dim(raw)[2]]
wecount

day = raw$day[1:which(raw$day=="NA")[1] - 1]
day

raww = raw[1:which(raw$day=="NA")[1] - 1, 3:dim(raw)[2]]
dim(raww)


```

```{r}
### First round: PH

# Locating the dates of PH

PH = which(day=="P")
ph_dr = vector()

for (i in PH) {
  ind = which(raww[i,]==2)
  dr = colnames(raww[,ind])
  print(c(dr, i))
  result[i] = dr
  count[,ind] = as.numeric(count[,ind]) - 1
  ph_dr = c(ph_dr, ind)
}

result
count
ph_dr
```

```{r}
### Second round: Weekend calls

# rules: all tier having the same chance
# (could be amended if needed)

# randomized list of weekends

rand = sample(which(raw$day=="E"))

# randomized list of doctors


count_t = count[,-ph_dr] ### those called for ph excluded
count_t = count_t[,which(count_t>0)] 

wedr = colnames(wecount)[which(wecount>0)]
count_t = count_t[,which(colnames(count_t) %in% wedr)] ### wecount == 0 excluded

dr = colnames(count_t)
q_dr = sample(dr)
q_dr

# filling the list

r_dr = vector()

for (i in rand) {
  
  for (j in q_dr) {
    try(if (j %in% r_dr) {next})
    
    m = 0
    
    illegal = (i-2):(i+2)
    illegal = illegal[which(illegal>0)]
    illegal = illegal[which(illegal<which(raw$day=="NA")[1])]
    filled = as.numeric(which(result==j))
    for (k in filled) {
      try(if (k %in% illegal) {m <- 1})
    }
    if (m==1) {next}
    
    idr = which(colnames(raww)==j)
    nocall = which(unlist(raww[,idr]==1))
    try(if (i %in% nocall) {next})
    
    print(c(j,i))
    result[i] = j
    count[,idr] = as.numeric(count[,idr]) - 1
    r_dr = c(r_dr, j)
    break
  }
}

result
```

```{r}
### Third round: for third tier 
# (specialists need at least 1 call)

# randomized list of weekdays

WD = which(day=="D" & is.na(result)==T) # excluding the filled dates
rand = sample(WD)

# randomized list of doctors

count_t = raw[ind_count, 3:dim(raw)[2]]
count_t = count_t[,which(count_t==1 & count==1)]
count_t
dr = colnames(count_t)
q_dr = sample(dr)
q_dr

# filling the list

r_dr = vector()

for (i in rand) {
  
  for (j in q_dr) {
    try(if (j %in% r_dr) {next})
    
    m = 0
    
    illegal = (i-2):(i+2)
    illegal = illegal[which(illegal>0)]
    illegal = illegal[which(illegal<which(raw$day=="NA")[1])]
    filled = as.numeric(which(result==j))
    for (k in filled) {
      try(if (k %in% illegal) {m <- 1})
    }
    if (m==1) {next}
    
    idr = which(colnames(raww)==j)
    nocall = which(unlist(raww[,idr]==1))
    try(if (i %in% nocall) {next})
    
    print(c(j,i))
    result[i] = j
    count[,idr] = as.numeric(count[,idr]) - 1
    r_dr = c(r_dr, j)
    break
  }
}

result
```


```{r}
### Fourth round: for first tier (count > 2)

# randomized list of weekdays

WD = which(day=="D" & is.na(result)==T) # excluding the filled dates
rand = sample(WD)

# randomized list of doctors

count_t = count
count_t = count_t[,which(count_t>2)]
count_t
dr = colnames(count_t)
q_dr = sample(dr)
q_dr

# filling the list

r_dr = vector()

for (i in rand) {
  
  for (j in q_dr) {
    try(if (j %in% r_dr) {next})
    
    m = 0
    
    illegal = (i-2):(i+2)
    illegal = illegal[which(illegal>0)]
    illegal = illegal[which(illegal<which(raw$day=="NA")[1])]
    filled = as.numeric(which(result==j))
    for (k in filled) {
      try(if (k %in% illegal) {m <- 1})
    }
    if (m==1) {next}
    
    idr = which(colnames(raww)==j)
    nocall = which(unlist(raww[,idr]==1))
    try(if (i %in% nocall) {next})
    
    print(c(j,i))
    result[i] = j
    count[,idr] = as.numeric(count[,idr]) - 1
    r_dr = c(r_dr, j)
    break
  }
}

result
```

```{r}
### Fifth round: for second tier (count > 1)

# randomized list of weekdays

WD = which(day=="D" & is.na(result)==T) # excluding the filled dates
rand = sample(WD)

# randomized list of doctors

count_t = count
count_t = count_t[,which(count_t>1)]
count_t
dr = colnames(count_t)
q_dr = sample(dr)
q_dr

# filling the list

r_dr = vector()

for (i in rand) {
  
  for (j in q_dr) {
    try(if (j %in% r_dr) {next})
    
    m = 0
    
    illegal = (i-2):(i+2)
    illegal = illegal[which(illegal>0)]
    illegal = illegal[which(illegal<which(raw$day=="NA")[1])]
    filled = as.numeric(which(result==j))
    for (k in filled) {
      try(if (k %in% illegal) {m <- 1})
    }
    if (m==1) {next}
    
    idr = which(colnames(raww)==j)
    nocall = which(unlist(raww[,idr]==1))
    try(if (i %in% nocall) {next})
    
    print(c(j,i))
    result[i] = j
    count[,idr] = as.numeric(count[,idr]) - 1
    r_dr = c(r_dr, j)
    break
  }
}

result
```

```{r}
### Sixth round: for second tier (count > 0)

# randomized list of weekdays

WD = which(day=="D" & is.na(result)==T) # excluding the filled dates
rand = sample(WD)

# randomized list of doctors

count_t = count
count_t = count_t[,which(count_t>0)]
count_t
dr = colnames(count_t)
q_dr = sample(dr)
q_dr

# filling the list

r_dr = vector()

for (i in rand) {
  
  for (j in q_dr) {
    try(if (j %in% r_dr) {next})
    
    m = 0
    
    illegal = (i-2):(i+2)
    illegal = illegal[which(illegal>0)]
    illegal = illegal[which(illegal<which(raw$day=="NA")[1])]
    filled = as.numeric(which(result==j))
    
    for (k in filled) {
      try(if (k %in% illegal) {m <- 1})
    }
    if (m==1) {next}
    
    idr = which(colnames(raww)==j)
    nocall = which(unlist(raww[,idr]==1))
    try(if (i %in% nocall) {next})
    
    print(c(j,i))
    result[i] = j
    count[,idr] = as.numeric(count[,idr]) - 1
    r_dr = c(r_dr, j)
    break
  }
}

resultf = data.frame(result)
rownames(resultf) = 1:dim(result)
resultf

write.csv(resultf,
          "call_list_result.csv", row.names = T)
```

```{r}
# goal
unlist(raw[ind_count, 3:dim(raw)[2]])
# result
table(result)
```
